// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6FPLxSHdWep0UhPBiODh8eXPDHIPClqc',
    appId: '1:450740351588:web:641a762c1177230e992571',
    messagingSenderId: '450740351588',
    projectId: 'dalel-eb638',
    authDomain: 'dalel-eb638.firebaseapp.com',
    storageBucket: 'dalel-eb638.appspot.com',
    measurementId: 'G-LWH0RX0QK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk43tChlraLcirx_xniMip1UlPYWB4O2M',
    appId: '1:450740351588:android:7320e77bf8b0c450992571',
    messagingSenderId: '450740351588',
    projectId: 'dalel-eb638',
    storageBucket: 'dalel-eb638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjd7xBihulUnTf-OEjv6VWFIJLw6lslVQ',
    appId: '1:450740351588:ios:9303ed3aca3a26b7992571',
    messagingSenderId: '450740351588',
    projectId: 'dalel-eb638',
    storageBucket: 'dalel-eb638.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjd7xBihulUnTf-OEjv6VWFIJLw6lslVQ',
    appId: '1:450740351588:ios:32412347cb3999b0992571',
    messagingSenderId: '450740351588',
    projectId: 'dalel-eb638',
    storageBucket: 'dalel-eb638.appspot.com',
    iosBundleId: 'com.example.dalelApp.RunnerTests',
  );
}
